version: '3.9'

services:
  php-apache:
    container_name: "php-apache"
    # image: "php:8.2.0-apache"
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8000:80
    depends_on:
      - db

  db:
    container_name: "db"
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Admin
      MYSQL_DATABASE: MyDatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: User_Pass
    ports:
      - 9906:3306
    
  phpmyadmin:
    container_name: "phpmyadmin"
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    depends_on:
      - db