version: '3.9'

services:
  php-apache:
    container_name: "php-apache"
    # image: "php:8.2.0-apache"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./wordpress:/var/www/html/
    ports:
      - 8000:80
    depends_on:
      - db

  # wordpress:
  #   image: wordpress
  #   restart: always
  #   environment:
  #     WORDPRESS_DB_HOST: db
  #     WORDPRESS_DB_NAME: MyDatabase
  #     WORDPRESS_DB_USER: user
  #     WORDPRESS_DB_PASSWORD: User_Pass
  #   volumes:
  #     - wordpress:/var/www/html
  #   ports:
  #     - 8080:80
  #   depends_on:
  #     - db

  db:
    container_name: "db"
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Admin
      MYSQL_DATABASE: MyDatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: User_Pass
    volumes:
      - db:/var/lib/mysql
    ports:
      - 9906:3306
    
  # phpmyadmin:
  #   container_name: "phpmyadmin"
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   ports:
  #     - 8081:80
  #   environment:
  #     PMA_HOST: db
  #   depends_on:
  #     - db

volumes:
    db: