version: '3.9'

services:
  php-apache:
    container_name: "php-apache"
    image: "php:8.2.0-apache"
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8080:80

  db:
    container_name: "db"
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - 9906:3306
    